### PR TITLE
Swap petra & crichton; add petra ipmi

### PR DESCRIPTION
**Pull request by clehner**
This updates the IP address for petra to better match existing usage and allocation.

### CODE REVIEW

**Comment by zgiles** [comment]
I see you're changing the IP of someone else's server.. 
Are you sure they're OK with that?
Originally added here...
https://github.com/nycmeshnet/nycmesh-dns/commit/de8a182c8d9764981887a16cc7a586ff0563ba37

**Comment by zgiles** [comment]
Do you have data that the IP has changed or was initially wrong? Are you know on the mesh, do you know myf, oliver, or jedahan? I don't see you on slack or having a server, so I'm missing context about how/why this change would get made..

**Comment by clehner** [comment]
Yes, I know these people.

micro confirmed to me privately that this change is okay.

To check, you can see the SSH banner of 10.70.90.86 suggesting what kind of device it is, and the web page on port 80 of 10.70.90.87 identifying itself.

**Comment by zgiles** [comment]
ok no problem. I agree, the IPs were backwards based on the ident etc.
Thx for responding, didn't know about any offline connections so it seemed to be from left field, had to check.

**Pull request merged**
